FROM python:3.11-slim-bullseye

WORKDIR /app

COPY services/rag_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/rag_api . 

COPY packages/shared-models ./packages/shared_models

RUN pip install -e ./packages/shared_models

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]